//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flatten
    {
        public int Id { get; set; }
        public string InstitutionName { get; set; }
        public string BusinessUnitName1 { get; set; }
        public string BusinessUnitName2 { get; set; }
        public string BusinessUnitName3 { get; set; }
    }
}
